---
title: "Experiment"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
library(splines)
library(ggplot2)
```

```{Rcpp}
// [[Rcpp::depends(RcppEigen)]]
#include <RcppEigen.h>
#include <iostream>
#include <algorithm>
using namespace std;

// [[Rcpp::export(testcpp)]]
void testcpp() {
  bool intercept;
  Rcpp::List mylist = Rcpp::List::create(Rcpp::Named("bool")=true);
  intercept = mylist["bool"];
  int a = 10;
  cout << intercept + a << endl;
}
```

+ curve fitting

```{r}
set.seed(1234)
knot = c(0.4,0.4,0.4,0.4,0.7)
beta = matrix(c(3,-5,5,-3,3,-5,3,-2),ncol=1)
# beta = matrix(c(3,-5,5,-3,3,-4),ncol=1)
m_train = 200; m_test = 50
```

```{r}
# generate train data set
x = c(0,sort(runif(m_train, 0, 1))[c(-1,-m_train)],1)
B = bs(x,knots=knot,Boundary.knots=c(0,1))
y = B%*%beta
y_h = y + rnorm(m_train,0,0.05)

# generate test data set
x_new = runif(m_test,0,1)
y_new = predict(B,x_new)%*%beta
```

```{r}
ggplot() + geom_point(aes(x,y_h))
```


```{r}
time_start = Sys.time()
a = ebars(x,y_h)
a$mcmc()
time_end = Sys.time()
print(time_end-time_start)
```

```{r}
a$knots()
```


```{r}
y_pred = a$predict(x_new)
sum((y_pred-y_new)^2)/m_test
```

```{r}
ggplot() + geom_point(aes(x_new,y_pred),color="red")
```

+ surface fitting

```{r}
set.seed(1234)
#tensor spline
beta = matrix(rnorm(40,0,1),ncol=1)
fss <- function(x,y){
  xix = c(0.2,0.5)
  xiy = c(0.4,0.4,0.4,0.4,0.7)
  B = tensor_spline(cbind(x,y),xix,xiy)
  return(B%*%beta)
}
```

```{r}
# parameters' configuration
m_train = 1000
m_test = 200
burns = 1000
steps = 1000
noise = 0.1
```

```{r}
x_1_grid <- x_2_grid <- seq(0, 1, length = 50)

y_grid <- outer(x_1_grid, x_2_grid, fss)
# plot the 3D surface
persp(x_1_grid, x_2_grid, y_grid, xlab="x_1",ylab="x_2",zlab="y",
      shade=0.75,main="perspective plot of Example 1")
```

```{r}
contour(x_1_grid, x_2_grid, y_grid, drawlabels = FALSE)
```

```{r}
image(x_1_grid, x_2_grid, y_grid)
```



```{r}
# generate train data set
x_1 = c(runif(m_train-2,0,1),0,1)
x_2 = c(runif(m_train-2,0,1),0,1)
y = fss(x_1,x_2)
y_h = y + rnorm(m_train,0,noise)
```

```{r}
# generate test set
x_1_new = runif(m_test,0,1)
x_2_new = runif(m_test,0,1)
y_new = fss(x_1_new,x_2_new)
```

```{r}
# run suface EBARS
time_start = Sys.time()
my_binebars = binebars(cbind(x_1,x_2), y_h)
my_binebars$mcmc()
time_end = Sys.time()
time_end - time_start
```

```{r}
my_binebars$knots()
```


```{r}
y_hat = my_binebars$predict(cbind(x_1_new,x_2_new))
sum((y_new-y_hat)^2)/m_test
```

```{r}
ebars_predict <- function(x,y) {
  return(my_binebars$predict(cbind(x,y)))
}
y_binebars = outer(x_1_grid,x_2_grid,ebars_predict)
```

```{r}
contour(x_1_grid, x_2_grid, y_binebars, drawlabels = FALSE)
```



```{r}
# kernel smooth method
library(sm)
sm = sm.regression(cbind(x_1,x_2),y_h,method="cv",eval.points=cbind(x_1_new,x_2_new),eval.grid=FALSE)
sum((y_new-sm$estimate)^2)/m_test
```

```{r}
my_sm = sm.regression(cbind(x_1,x_2),y_h,method="cv",eval.points=cbind(rep(x_1_grid,times=50),rep(x_2_grid,each=50)),eval.grid=FALSE)
y_grid_sm = matrix(my_sm$estimate, 50, 50)
```

```{r}
contour(x_1_grid, x_2_grid, y_grid_sm, drawlabels = FALSE)
```


```{r}
# local polynomial regression method
df = data.frame(x=x_1,y=x_2,z=y_h)
locpm = loess(z~x*y,data=df,degree=2,span=0.05)
#control = loess.control(surface = "direct")
y_locpm = predict(locpm,cbind(x_1_new,x_2_new))
sum((y_new-y_locpm)^2)/m_test
```

```{r}
locp_predict <- function(x,y) {
  return(predict(locpm, cbind(x,y)))
}
```

```{r}
contour(x_1_grid, x_2_grid, outer(x_1_grid,x_2_grid,locp_predict), drawlabels = FALSE)
```

# manifold fitting

```{r}
set.seed(1234)
```

```{r}
# Simulated data
I=1000                              # Sample size
t=rnorm(I,mean = 0,sd=1)
sd.noise=0.15                       # Standard deviation of the noise 
e1=rnorm(I,mean = 0,sd=sd.noise)    # noise
e2=rnorm(I,mean = 0,sd=sd.noise)
X=matrix(NA,ncol = 2,nrow = I)
manifold=function(tau){ return(c(tau,sin(tau+pi/2))) }
for(i in 1:I){ X[i,]=manifold(t[i]) }
data.points=X+cbind(e1,e2) 
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
```


```{r}
result=PME(x.obs=data.points, d=1)
```

```{r}
# Plot the fitted manifold
f=result$embedding.map
t.test=seq(from=-100,to=100,by=0.05)
t.length=length(t.test)
x.test=matrix(NA,ncol=2,nrow = t.length)
for(i in 1:t.length){ x.test[i,]=f(t.test[i]) }
```

```{r}
res = manifold_fitting(x=data.points,d=1)
```

```{r}
x_test = res$map(seq(-3,3,length.out=500))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
lines(x_test[,1],x_test[,2],col="red",type = "l",lwd=3)
```

+ Case II

```{r}
set.seed(1234)
```

```{r}
# Simulated data
I=500                              # Sample size
theta = runif(I,-pi/2,0)
x = matrix(NA,2*I,2)
for(i in c(1:I)) {x[i,]=c(-1+cos(theta[i]),1+sin(theta[i]))}
alpha = runif(I, -pi, -pi/2)
for(i in c(1:I)) {x[(I+i),]=c(1+cos(alpha[i]),1+sin(alpha[i]))}
```

```{r}
sd.noise = 0.025
e1 = rnorm(2*I,0,sd.noise)
e2 = rnorm(2*I,0,sd.noise)
data.points = x + cbind(e1,e2)
```


```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
```

```{r}
result=PME(x.obs=data.points, d=1)
```

```{r}
# Plot the fitted manifold
f=result$embedding.map
t.test=seq(from=-100,to=100,by=0.05)
t.length=length(t.test)
x.test=matrix(NA,ncol=2,nrow = t.length)
for(i in 1:t.length){ x.test[i,]=f(t.test[i]) }
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
```

```{r}
res = manifold_fitting(x=data.points,d=1)
```

```{r}
center = (res$lower+res$upper)/2
radius = abs(res$upper-res$lower)/2
x_test = res$map(seq(center-radius*0.95,center+radius*0.95,length.out=500))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
lines(x_test[,1],x_test[,2],col="red",type = "l",lwd=3)
```

+ Case III

```{r}
### Case II

manifold=function(t){ return(c(cos(t),sin(t)))}
I=1000
t=runif(I,min = 0,max = 1.5*pi)
X=manifold(t)
sd.noise=0.1
e1=rnorm(I,mean = 0, sd=sd.noise)
e2=rnorm(I,mean = 0, sd=sd.noise)
data.points=X+cbind(e1,e2)  
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
```


```{r}
result=PME(x.obs=data.points, d=1)
```


```{r}
f=result$embedding.map
t.test=seq(from=-100,to=100,by=0.05)
t.length=length(t.test)
x.test=matrix(NA,ncol=2,nrow = t.length)
for(i in 1:t.length){ x.test[i,]=f(t.test[i]) }
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="red",type = "l",lwd=3)
```

```{r}
res = manifold_fitting(x=data.points,d=1)
```

```{r}
center = (res$lower+res$upper)/2
radius = abs(res$upper-res$lower)/2
x_test = res$map(seq(center-radius*0.95,center+radius*0.95,length.out=500))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
lines(x_test[,1],x_test[,2],col="red",type = "l",lwd=3)
```

+ Spiral
```{r}
set.seed(1234)
```

```{r}
I = 1000
theta = seq(0, 6*pi, length.out=I)
X = cbind((theta+4)^(0.7)*cos(theta), (theta+4)^(0.7)*sin(theta))
```

```{r}
sd.noise = 0.15
data.points = X + cbind(rnorm(I,0,sd.noise), rnorm(I,0,sd.noise))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
```

```{r}
result=PME(x.obs=data.points, d=1)
```

```{r}
f=result$embedding.map
t.test=seq(from=-100,to=100,by=0.05)
t.length=length(t.test)
x.test=matrix(NA,ncol=2,nrow = t.length)
for(i in 1:t.length){ x.test[i,]=f(t.test[i]) }
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="red",type = "l",lwd=3)
```

```{r}
res = manifold_fitting(x=data.points,d=1)
```

```{r}
center = (res$lower+res$upper)/2
radius = abs(res$upper-res$lower)/2
x_test = res$map(seq(center-radius*0.99,center+radius*0.99,length.out=500))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
lines(x_test[,1],x_test[,2],col="red",type = "l",lwd=3)
```

```{r}
I=1000                             
t=runif(I, min = -3*pi, max = 3*pi)
sd.noise=0.1                       
e1=rnorm(I,mean = 0,sd=sd.noise)    
e2=rnorm(I,mean = 0,sd=sd.noise)
X=matrix(NA,ncol = 2,nrow = I)
manifold=function(tau){ return(c(tau,sin(tau))) }
for(i in 1:I){ X[i,]=manifold(t[i]) }
data.points=X+cbind(e1,e2) 
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
```

```{r}
result=PME(x.obs=data.points, d=1)
```

```{r}
f=result$embedding.map
t.test=seq(from=-100,to=100,by=0.05)
t.length=length(t.test)
x.test=matrix(NA,ncol=2,nrow = t.length)
for(i in 1:t.length){ x.test[i,]=f(t.test[i]) }
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="red",type = "l",lwd=3)
```

```{r}
res = manifold_fitting(x=data.points,d=1)
```

```{r}
center = (res$lower+res$upper)/2
radius = abs(res$upper-res$lower)/2
x_test = res$map(seq(center-radius*0.99,center+radius*0.99,length.out=500))
```

```{r}
plot(data.points[,1], data.points[,2],
     pch=20, col="grey",
     main="Principal Manifold Estimation",
     xlab=" ", ylab=" ")
lines(x.test[,1],x.test[,2],col="blue",type = "l",lwd=3)
lines(x_test[,1],x_test[,2],col="red",type = "l",lwd=3)
```
