// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tensor_spline
Eigen::MatrixXd tensor_spline(const Eigen::MatrixXd& x, const std::vector<Eigen::VectorXd>& xis, std::vector<int> degrees, Rcpp::LogicalVector intercepts, const Eigen::RowVectorXd& xmin, const Eigen::RowVectorXd& xmax);
RcppExport SEXP _ABMRS_tensor_spline(SEXP xSEXP, SEXP xisSEXP, SEXP degreesSEXP, SEXP interceptsSEXP, SEXP xminSEXP, SEXP xmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::VectorXd>& >::type xis(xisSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< const Eigen::RowVectorXd& >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< const Eigen::RowVectorXd& >::type xmax(xmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_spline(x, xis, degrees, intercepts, xmin, xmax));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_class_EBARS();
RcppExport SEXP _rcpp_module_boot_class_MEBARS();

static const R_CallMethodDef CallEntries[] = {
    {"_ABMRS_tensor_spline", (DL_FUNC) &_ABMRS_tensor_spline, 6},
    {"_rcpp_module_boot_class_EBARS", (DL_FUNC) &_rcpp_module_boot_class_EBARS, 0},
    {"_rcpp_module_boot_class_MEBARS", (DL_FUNC) &_rcpp_module_boot_class_MEBARS, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ABMRS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
