# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ClassEBARS
#' @title extended Bayesian adaptive regression univariate spline
#' @description a cpp class
#'
#' @field new constructor, see `ebars`
#' @field rjmcmc run reversible jump MCMC algorithm
#' @field predict predict posterior response values for new data
#' @field knots get posterior samples of knots
#' @field coefs get posterior samples of regression coefficients
#' @field resids get posterior samples of residual standard deviations
NULL

#' @name ClassMEBARS
#' @title extended Bayesian adaptive regression multivariate spline
#' @description a cpp class
#'
#' @field new constructor, see `mebars`
#' @field rjmcmc run reversible jump MCMC algorithm
#' @field predict predict posterior response values for new data
#' @field knots get posterior samples of knots
#' @field coefs get posterior samples of regression coefficients
#' @field resids get posterior samples of residual standard deviations
NULL

#' create a univariate B-spline basis matrix
#' @param x a numeric vector of predictor values.
#' @param xi a numeric vector, indicates the knots.
#' @param degree int, the degree of polynomial, default value is `3`.
#' @param intercept bool, whether the intercept is included in the basis, default value is `FALSE`.
#'
#' @returns a B-spline basis matrix.
#' @export
spline <- function(x, xi, degree, intercept) {
    .Call(`_ABMRS_spline`, x, xi, degree, intercept)
}

#' create a general tensor product spline basis matrix for arbitrary dimensions
#' @param x a numeric matrix, (m,d), each row indicates a predictor value.
#' @param xis a list of numeric vectors, each element contains knots for one dimension.
#' @param degrees an integer vector, degrees for each dimension.
#' @param intercepts a logical vector, whether intercepts are included for each dimension.
#'
#' @returns a tensor product B-spline basis matrix.
#'
#' @export
#' @examples
#' # 2D example
#' x <- matrix(runif(100), ncol=2)
#' xis <- list(c(0.3, 0.6), c(0.4, 0.5))
#' B <- tensor_spline(x, xis, c(3,3), c(FALSE,FALSE))
#' 
#' # 3D example
#' x <- matrix(runif(150), ncol=3)
#' xis <- list(c(0.2, 0.5), c(0.3, 0.7), c(0.4))
#' B <- tensor_spline(x, xis, c(3,3,3), c(TRUE,TRUE,TRUE))
tensor_spline <- function(x, xis, degrees, intercepts) {
    .Call(`_ABMRS_tensor_spline`, x, xis, degrees, intercepts)
}

