# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ClassBinEBARS
#' @title bivariate extended Bayesian adaptive regression spline
#' @description a class of [binebars()]
#'
#' @field new constructor, see `binebars`
#' @field rjmcmc reversible jump MCMC, a wrapper is `mcmc`
#' @field predict predict by surface spline regression with EBARS
#' @field knots return estimated knots
NULL

#' @name ClassEBARS
#' @title extended Bayesian adaptive regression spline
#' @description a class of [ebars()]
#'
#' @field new constructor, see `ebars`
#' @field rjmcmc reversible jump MCMC, a wrapper is `mcmc`
#' @field predict predict by spline regression with EBARS
#' @field knots return estimated knots
NULL

#' create a bivariate tensor product spline basis matrix
#' @param x a numeric matrix, (m,2), each row indicates a predictor value (x_1,x_2).
#' @param xi_1 a numeric vector, indicates `k_1` knots in x_1.
#' @param xi_2 a numeric vector, indicates `k_2` knots in x_2
#'
#' @returns a bivariate tensor product spline basis matrix, m rows and (k_1+3)*(k_2+3) cols.
#'
#' @export
tensor_spline <- function(x, xi_1, xi_2) {
    .Call(`_EBARS_tensor_spline`, x, xi_1, xi_2)
}

